language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: pDta0UmJzuU86LFo/2R5WH+l61WsqeaAOSCTMD8L6JBrct74h3ZeX963U9P3SAg0ZVRwpIR+6QPofBhMV2jvcQq6k7q6iU8nliqLUqp5cASCyKU/B0rQ9YZMOuYd5NswSSF34cipYvkjs0sccKYUMriUy4+K1FuvoHnG4aEgidPpB/ClWXgjXs1jTqv1AiXcIq9pX1eoaK3Ids7OvO9XKnInYJryF3J6jFr6acxtEobsGK3RNgBog5CYPCqRT83bk8FDHPKBfsYdTkyBsUhNKO2nWnFrJGYITsabA7oOrz8QTFyP47H6voRI5AHkkrnimw9Rg+N4ZuoIkGJEctSE+ukkhKlGx4To3xkhN7XPIoCB7BWkqrdLSUZGuswMYmpd/M6JwbQyaHvBeqf6QBEuI/YKoq2OpYKB6uEQWrWvT9Ss3+9d3FxtJ//VsPvvLtXazn9JOl20BzqxSURDpAxC6TDe1sQhbuQWfCVXJtsvCt+9e2yiVlSuK0db+E6Q0F8RbqoBrW/zwDeWE3eh3+0UDEKmVAL4P7wrqoTpjEwe2Ubpvx0oZEsTDGY7ktqw0Ezkt5TR4fkvm2UQf0io+QOo1rcT/BuwxhUs1i41N98TfFyZq+B4JtTeyARDpDaDl+qT2D5XMUhuf4yutq+G813G0bVHwoRo27fJynkHbG8me7o=
  app: prevengic
  on:
    repo: manudevelopia/prevengic
