
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
