GET localhost:8080/api/reports/all

###

POST localhost:8080/api/reports/create
Content-Type: application/json

[
  {
    "name": "Acetaldehído",
    "concentration": "1",
    "exposition": "1"
  }
]


###

